// CodeVibe 3D — Banco de dados de desafios (50 missões)
// Baseado estritamente nas Cheat Sheets: HTML, CSS, JavaScript e VS Code.
// resposta_correta = índice da opção correta em `opcoes`.

export const TRACKS = [
  { id: "html", nome: "HTML", sub: "A estrutura de tudo", cor: "#ff6a3d", icone: "code" },
  { id: "css", nome: "CSS", sub: "Estilo e layout", cor: "#22d3ee", icone: "palette" },
  { id: "js", nome: "JavaScript", sub: "Lógica e vida", cor: "#facc15", icone: "zap" },
  { id: "vscode", nome: "VS Code", sub: "Produtividade ninja", cor: "#c084fc", icone: "keyboard" },
];

export const CHALLENGES = [
  // ─────────────── HTML (10) ───────────────
  {
    id: 1, categoria: "html", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "MISSÃO 01 // O portal não abre. Todo documento HTML precisa declarar sua identidade na primeira linha para o navegador saber que é HTML5. Complete a declaração.",
    codigo_base: "____\n<html lang=\"pt-BR\">\n  <head>...</head>\n  <body>...</body>\n</html>",
    opcoes: ["<!DOCTYPE html>", "<doctype html5>", "<html doctype>", "<!DOC html>"],
    resposta_correta: 0,
    dica: "Está no topo da cheat sheet: toda página HTML DEVE começar com a declaração do tipo do documento. É <!DOCTYPE html> — simples assim.",
  },
  {
    id: 2, categoria: "html", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "MISSÃO 02 // A aba do navegador está sem nome. Dentro do <head>, existe uma tag que define o título que aparece na aba. Qual é ela?",
    codigo_base: "<head>\n  <meta charset=\"UTF-8\">\n  <____>Minha Página</____>\n</head>",
    opcoes: ["header", "title", "name", "h1"],
    resposta_correta: 1,
    dica: "Não confunda: <h1> é o título VISÍVEL na página, <header> é uma seção. O que nomeia a ABA fica no <head> e se chama <title>.",
  },
  {
    id: 3, categoria: "html", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "MISSÃO 03 // Hierarquia é poder. Você precisa do título MAIS IMPORTANTE (e maior) da página. Qual tag de heading usar?",
    codigo_base: "<body>\n  <____>Hello, World!</____>\n  <p>Meu primeiro site.</p>\n</body>",
    opcoes: ["<h6>", "<heading>", "<h1>", "<big>"],
    resposta_correta: 2,
    dica: "Os headings vão de h1 a h6. Quanto MENOR o número, MAIOR a importância. O chefe é o <h1>.",
  },
  {
    id: 4, categoria: "html", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 04 // O link está sequestrando o usuário da sua página! Faça o link abrir em uma NOVA ABA, sem fechar a atual.",
    codigo_base: "<a href=\"https://example.com\"\n   ____>\n  Visitar Site\n</a>",
    opcoes: ["newtab=\"true\"", "target=\"_blank\"", "open=\"new\"", "href=\"_blank\""],
    resposta_correta: 1,
    dica: "O atributo é target. E o valor mágico para nova aba é \"_blank\". Juntos: target=\"_blank\".",
  },
  {
    id: 5, categoria: "html", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 05 // Acessibilidade é superpoder. Se a imagem não carregar (ou alguém usar leitor de tela), um atributo descreve o que ela mostra. Qual?",
    codigo_base: "<img src=\"logo.png\"\n     ____=\"Logo da empresa\"\n     width=\"200\">",
    opcoes: ["alt", "title", "desc", "text"],
    resposta_correta: 0,
    dica: "TIP da cheat sheet: 'Always use meaningful ALT text for images'. É o atributo alt — bom para acessibilidade E para SEO.",
  },
  {
    id: 6, categoria: "html", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "MISSÃO 06 // Você precisa de um ranking: 1º, 2º, 3º... A ordem IMPORTA. Qual tag cria uma lista ORDENADA (numerada)?",
    codigo_base: "<____>\n  <li>Primeiro</li>\n  <li>Segundo</li>\n  <li>Terceiro</li>\n</____>",
    opcoes: ["<ul>", "<list>", "<dl>", "<ol>"],
    resposta_correta: 3,
    dica: "ul = Unordered List (bolinhas). ol = Ordered List (números). Para ranking, você quer a ordenada: <ol>.",
  },
  {
    id: 7, categoria: "html", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 07 // O formulário de login precisa validar e-mails automaticamente. Qual type do <input> ativa essa validação nativa?",
    codigo_base: "<form action=\"/submit\" method=\"post\">\n  <label for=\"email\">Email:</label>\n  <input type=\"____\" id=\"email\" required>\n</form>",
    opcoes: ["text", "email", "mail", "validate"],
    resposta_correta: 1,
    dica: "A cheat sheet lista os input types comuns: text, email, password, number, checkbox... Para e-mail com validação grátis, use type=\"email\".",
  },
  {
    id: 8, categoria: "html", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 08 // Tags semânticas deixam seu site profissional. Qual tag é feita ESPECIFICAMENTE para agrupar os links de navegação?",
    codigo_base: "<header>\n  <____>\n    <a href=\"/\">Home</a>\n    <a href=\"/sobre\">Sobre</a>\n  </____>\n</header>",
    opcoes: ["<nav>", "<menu>", "<links>", "<aside>"],
    resposta_correta: 0,
    dica: "Semântica: <header> topo, <nav> navegação, <main> conteúdo principal, <footer> rodapé. Para links de navegação: <nav>.",
  },
  {
    id: 9, categoria: "html", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "MISSÃO 09 // Deixe recados secretos no código! Comentários não aparecem no navegador, só para quem lê o código. Qual é a sintaxe?",
    codigo_base: "____ Este é um comentário ____\n<p>Este texto aparece.</p>",
    opcoes: ["// ... //", "/* ... */", "<!-- ... -->", "# ... #"],
    resposta_correta: 2,
    dica: "Cada linguagem tem seu estilo: JS usa //, CSS usa /* */. No HTML é <!-- comentário -->.",
  },
  {
    id: 10, categoria: "html", dificuldade: "Difícil", xp: 100,
    pergunta_imersiva: "MISSÃO 10 // Seu site está quebrado no celular! Falta a meta tag no <head> que torna a página responsiva. Complete o atributo content.",
    codigo_base: "<meta name=\"viewport\"\n      content=\"width=____,\n      initial-scale=1.0\">",
    opcoes: ["100%", "device-width", "mobile", "responsive"],
    resposta_correta: 1,
    dica: "A cheat sheet mostra: content=\"width=device-width, initial-scale=1.0\". Isso diz ao navegador: use a largura REAL do aparelho.",
  },

  // ─────────────── CSS (10) ───────────────
  {
    id: 11, categoria: "css", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "MISSÃO 01 // Você criou <div class=\"card\"> e precisa estilizá-la. Qual seletor CSS mira em uma CLASSE?",
    codigo_base: "____ {\n  background: #0d6efd;\n  padding: 20px;\n}",
    opcoes: ["#card", ".card", "card", "*card"],
    resposta_correta: 1,
    dica: "Tabela de seletores: # é para ID, . (ponto) é para classe, * pega tudo. Classe = .card",
  },
  {
    id: 12, categoria: "css", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 02 // O clássico: centralizar! Com flexbox, qual propriedade centraliza os itens no eixo HORIZONTAL (principal)?",
    codigo_base: ".container {\n  display: flex;\n  ____: center;\n  align-items: center;\n}",
    opcoes: ["justify-content", "text-align", "center-items", "flex-align"],
    resposta_correta: 0,
    dica: "Dupla dinâmica do flexbox: justify-content = eixo principal (horizontal), align-items = eixo cruzado (vertical).",
  },
  {
    id: 13, categoria: "css", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 03 // Construa uma galeria com 3 colunas de larguras IGUAIS usando CSS Grid. Qual valor usar?",
    codigo_base: ".galeria {\n  display: grid;\n  grid-template-columns: ____;\n  gap: 15px;\n}",
    opcoes: ["3 columns", "33% 33% 33%", "1fr 1fr 1fr", "auto-3"],
    resposta_correta: 2,
    dica: "fr = fração do espaço disponível. 1fr 1fr 1fr divide em 3 partes iguais (e já respeita o gap, diferente de %).",
  },
  {
    id: 14, categoria: "css", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "MISSÃO 04 // Box Model: o texto está colado na borda do card. Qual propriedade cria espaço INTERNO (entre o conteúdo e a borda)?",
    codigo_base: ".card {\n  border: 2px solid #333;\n  ____: 20px;\n}",
    opcoes: ["margin", "spacing", "gap", "padding"],
    resposta_correta: 3,
    dica: "Box model de dentro para fora: content → PADDING → border → MARGIN. Espaço interno = padding.",
  },
  {
    id: 15, categoria: "css", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "MISSÃO 05 // Interatividade! O botão deve mudar de cor quando o mouse passar por cima. Qual pseudo-classe usar?",
    codigo_base: ".botao____ {\n  background: #ff5722;\n  transform: scale(1.1);\n}",
    opcoes: [":hover", ":mouse", ":over", ":active"],
    resposta_correta: 0,
    dica: "Pseudo-classes da cheat sheet: :hover (mouse em cima), :active (clicando), :focus (selecionado). Mouse em cima = :hover.",
  },
  {
    id: 16, categoria: "css", dificuldade: "Difícil", xp: 100,
    pergunta_imersiva: "MISSÃO 06 // O menu deve rolar junto com a página e GRUDAR no topo ao chegar lá. Qual position faz isso?",
    codigo_base: ".menu {\n  position: ____;\n  top: 0;\n}",
    opcoes: ["fixed", "absolute", "sticky", "relative"],
    resposta_correta: 2,
    dica: "fixed fica preso na tela SEMPRE. sticky rola normal e 'gruda' quando atinge o topo — (sticks on scroll), diz a cheat sheet.",
  },
  {
    id: 17, categoria: "css", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 07 // Animações suaves separam amadores de profissionais. Complete para animar TODAS as mudanças em 0.3 segundos.",
    codigo_base: ".card {\n  ____: all 0.3s ease;\n}\n.card:hover {\n  transform: scale(1.1);\n}",
    opcoes: ["animation", "transition", "transform", "duration"],
    resposta_correta: 1,
    dica: "transform MUDA o elemento (scale, rotate). transition SUAVIZA a mudança. Para suavizar: transition: all 0.3s ease.",
  },
  {
    id: 18, categoria: "css", dificuldade: "Difícil", xp: 100,
    pergunta_imersiva: "MISSÃO 08 // Modo responsivo ativado! Aplique estilos SOMENTE em telas de celular (até 600px). Complete a media query.",
    codigo_base: "@media (____: 600px) {\n  .container {\n    width: 100%;\n    padding: 10px;\n  }\n}",
    opcoes: ["screen-size", "max-width", "mobile", "min-width"],
    resposta_correta: 1,
    dica: "max-width: 600px = 'ATÉ 600px' (celular). min-width: 601px = 'A PARTIR de 601px' (tablet+). Para celular: max-width.",
  },
  {
    id: 19, categoria: "css", dificuldade: "Difícil", xp: 100,
    pergunta_imersiva: "MISSÃO 09 // CSS Variables: defina a cor uma vez, use em todo lugar. Como USAR a variável --primary definida no :root?",
    codigo_base: ":root {\n  --primary: #0d6efd;\n}\nbody {\n  color: ____;\n}",
    opcoes: ["--primary", "var(--primary)", "$primary", "get(--primary)"],
    resposta_correta: 1,
    dica: "Declarar: --primary: valor. Usar: var(--primary). A função var() é obrigatória na hora de usar. 'Reusable & Easy to Maintain!'",
  },
  {
    id: 20, categoria: "css", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 10 // Unidades relativas = design responsivo. Qual unidade é relativa ao tamanho da fonte RAIZ (root) do documento?",
    codigo_base: "h1 {\n  font-size: 2____;\n  /* 2x a fonte raiz */\n}",
    opcoes: ["px", "em", "rem", "vh"],
    resposta_correta: 2,
    dica: "em = relativo à fonte do PAI. rem = relativo à fonte da RAIZ (root em). Tip da cheat sheet: 'Use rem and % for responsive design'.",
  },

  // ─────────────── JavaScript (10) ───────────────
  {
    id: 21, categoria: "js", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "MISSÃO 01 // Declare uma variável que NUNCA mudará de valor. Se alguém tentar alterar, o código deve dar erro. Qual palavra-chave?",
    codigo_base: "____ PI = 3.14159;\n// PI nunca deve mudar!",
    opcoes: ["let", "var", "const", "static"],
    resposta_correta: 2,
    dica: "Quick Tip da cheat sheet: 'Use const by default, let when needed'. Constante = const.",
  },
  {
    id: 22, categoria: "js", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 02 // Comparação PERFEITA: o operador que compara valor E tipo (5 é diferente de '5'). Qual é?",
    codigo_base: "console.log(5 ____ \"5\");\n// deve retornar: false",
    opcoes: ["==", "===", "=", "!=="],
    resposta_correta: 1,
    dica: "== compara só o valor (5 == '5' é true 😱). === compara valor E tipo. Quick Tip: 'Use === instead of =='.",
  },
  {
    id: 23, categoria: "js", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 03 // Arrow functions: o jeito moderno e compacto. Complete a função que soma dois números.",
    codigo_base: "const add = (a, b) ____ a + b;\n\nconsole.log(add(2, 3)); // 5",
    opcoes: ["->", "=>", ":", "return"],
    resposta_correta: 1,
    dica: "Arrow function usa a 'flecha gorda': =>. Sem chaves, o retorno é implícito: (a, b) => a + b.",
  },
  {
    id: 24, categoria: "js", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "MISSÃO 04 // Seu array de frutas precisa de mais um item NO FINAL. Qual método usar?",
    codigo_base: "let fruits = [\"Apple\", \"Banana\"];\nfruits.____(\"Orange\");\n// [\"Apple\", \"Banana\", \"Orange\"]",
    opcoes: ["push", "pop", "add", "append"],
    resposta_correta: 0,
    dica: "push = adiciona no final. pop = REMOVE do final. shift/unshift mexem no começo. Para adicionar: push.",
  },
  {
    id: 25, categoria: "js", dificuldade: "Difícil", xp: 100,
    pergunta_imersiva: "MISSÃO 05 // Transforme TODOS os itens do array de uma vez: dobre cada número. Qual método cria um novo array transformado?",
    codigo_base: "let nums = [1, 2, 3];\nlet dobro = nums.____(n => n * 2);\n// [2, 4, 6]",
    opcoes: ["filter", "map", "forEach", "reduce"],
    resposta_correta: 1,
    dica: "map TRANSFORMA cada item e devolve um novo array. filter SELECIONA itens. reduce REDUZ a um valor só. Transformar = map.",
  },
  {
    id: 26, categoria: "js", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 06 // DOM Selection: capture o elemento <h1 id=\"titulo\"> para manipulá-lo com JS. Complete o comando.",
    codigo_base: "let titulo = document\n  .____(\"titulo\");",
    opcoes: ["querySelector", "getElementById", "getElement", "selectById"],
    resposta_correta: 1,
    dica: "Para ID existe o método direto: getElementById(\"titulo\") — sem # ! (querySelector também funciona, mas aí seria \"#titulo\").",
  },
  {
    id: 27, categoria: "js", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "MISSÃO 07 // Mude o TEXTO de um elemento via JavaScript. Qual propriedade altera o conteúdo de texto?",
    codigo_base: "document.getElementById(\"msg\")\n  .____ = \"Você venceu!\";",
    opcoes: ["innerText()", "textContent", "text", "value"],
    resposta_correta: 1,
    dica: "A cheat sheet mostra em 'Change content': elemento.textContent = \"Hello\". É uma propriedade (sem parênteses!).",
  },
  {
    id: 28, categoria: "js", dificuldade: "Difícil", xp: 100,
    pergunta_imersiva: "MISSÃO 08 // Eventos dão vida ao site! Faça o botão REAGIR ao clique. Complete o método.",
    codigo_base: "document.querySelector(\"button\")\n  .____(\"click\", () => {\n    alert(\"Button Clicked!\");\n  });",
    opcoes: ["onClick", "addEventListener", "listen", "onEvent"],
    resposta_correta: 1,
    dica: "O método universal de eventos: addEventListener(\"evento\", função). Eventos comuns: click, submit, keypress, mouseover, change, load.",
  },
  {
    id: 29, categoria: "js", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "MISSÃO 09 // GRITE! Converta o texto para CAIXA ALTA usando um string method.",
    codigo_base: "let text = \"JavaScript is Awesome\";\ntext.____();\n// \"JAVASCRIPT IS AWESOME\"",
    opcoes: ["toUpperCase", "upperCase", "toCaps", "allCaps"],
    resposta_correta: 0,
    dica: "String methods da cheat sheet: toUpperCase() grita, toLowerCase() sussurra, includes() procura, slice() recorta.",
  },
  {
    id: 30, categoria: "js", dificuldade: "Difícil", xp: 100,
    pergunta_imersiva: "MISSÃO 10 // Missão temporal: execute o código com 2 segundos de ATRASO (delay). Qual atalho da cheat sheet usar?",
    codigo_base: "____(() => {\n  console.log(\"Boom! 💥\");\n}, 2000);",
    opcoes: ["setInterval", "delay", "setTimeout", "wait"],
    resposta_correta: 2,
    dica: "setTimeout = executa UMA vez após o delay. setInterval = REPETE a cada intervalo. Delay único = setTimeout.",
  },

  // ─────────────── VS Code (20) ───────────────
  {
    id: 31, categoria: "vscode", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "ATALHO 01 // Novo projeto, nova ideia! Crie um arquivo novo INSTANTANEAMENTE, sem tocar no mouse.",
    codigo_base: "// Ação: New File\n// Criar um arquivo novo rapidamente\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + N", "Ctrl + F", "Alt + N", "Ctrl + Shift + N"],
    resposta_correta: 0,
    dica: "N de NEW. Ctrl + N = novo arquivo. Um dos atalhos mais usados do mundo.",
  },
  {
    id: 32, categoria: "vscode", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "ATALHO 02 // Abra qualquer arquivo do seu computador direto no editor. Qual combinação?",
    codigo_base: "// Ação: Open File\n// Abrir arquivos instantaneamente\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + A", "Ctrl + O", "Alt + O", "Ctrl + P"],
    resposta_correta: 1,
    dica: "O de OPEN. Ctrl + O abre a janela de seleção de arquivo.",
  },
  {
    id: 33, categoria: "vscode", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "ATALHO 03 // A variável 'userData' está perdida em algum dos 200 arquivos do projeto. Busque em TODOS os arquivos de uma vez!",
    codigo_base: "// Ação: Search in Files\n// Buscar em TODO o projeto\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + F", "Ctrl + Shift + F", "Ctrl + G", "Alt + F"],
    resposta_correta: 1,
    dica: "Ctrl + F busca no arquivo ATUAL. Adicione Shift para expandir a busca ao projeto INTEIRO: Ctrl + Shift + F.",
  },
  {
    id: 34, categoria: "vscode", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "ATALHO 04 // Hora de commitar seu código! Abra o painel de Source Control (Git) sem sair do teclado.",
    codigo_base: "// Ação: Open Source Control\n// Painel do Git\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + G", "Ctrl + Shift + G", "Ctrl + Alt + G", "F8"],
    resposta_correta: 1,
    dica: "G de GIT. Ctrl + Shift + G abre o painel de controle de versão.",
  },
  {
    id: 35, categoria: "vscode", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "ATALHO 05 // Momento da verdade: rode e debugue sua aplicação com UMA tecla.",
    codigo_base: "// Ação: Run / Debug\n// Iniciar o debug da aplicação\n\n[ PRESSIONE: ____ ]",
    opcoes: ["F5", "F12", "Ctrl + R", "F9"],
    resposta_correta: 0,
    dica: "Uma tecla só: F5. A mesma que recarrega o navegador inicia o debug no VS Code.",
  },
  {
    id: 36, categoria: "vscode", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "ATALHO 06 // Compare dois arquivos lado a lado: divida o editor em duas partes.",
    codigo_base: "// Ação: Split Editor\n// Dividir o editor em dois\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + D", "Ctrl + \\", "Ctrl + S", "Alt + 2"],
    resposta_correta: 1,
    dica: "A barra invertida \\ parece uma divisória, certo? Ctrl + \\ divide o editor.",
  },
  {
    id: 37, categoria: "vscode", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "ATALHO 07 // Preguiça produtiva: duplique a linha atual sem copiar e colar!",
    codigo_base: "// Ação: Duplicate Line\n// Duplicar a linha ou seleção\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + C, Ctrl + V", "Shift + Alt + ↓", "Ctrl + D", "Alt + D"],
    resposta_correta: 1,
    dica: "Shift + Alt + ↓ clona a linha para baixo. Muito mais rápido que Ctrl+C / Ctrl+V!",
  },
  {
    id: 38, categoria: "vscode", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "ATALHO 08 // A linha está no lugar errado! MOVA a linha atual para cima ou para baixo sem recortar nada.",
    codigo_base: "// Ação: Move Line Up / Down\n// Mover a linha atual\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + ↑ / ↓", "Alt + ↑ / ↓", "Shift + ↑ / ↓", "Tab + ↑ / ↓"],
    resposta_correta: 1,
    dica: "Alt + setas move a linha como um elevador. Alt + ↑ sobe, Alt + ↓ desce.",
  },
  {
    id: 39, categoria: "vscode", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "ATALHO 09 // Código morto detectado! DELETE a linha inteira de uma vez, sem selecionar nada.",
    codigo_base: "// Ação: Delete Line\n// Apagar a linha inteira\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + Shift + K", "Delete", "Ctrl + X", "Alt + Del"],
    resposta_correta: 0,
    dica: "K de KILL 🔪. Ctrl + Shift + K elimina a linha inteira instantaneamente.",
  },
  {
    id: 40, categoria: "vscode", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "ATALHO 10 // Silencie uma linha de código! Comente/descomente a linha atual com um atalho.",
    codigo_base: "// Ação: Comment Line\n// Comentar/descomentar linha\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + ;", "Ctrl + /", "Ctrl + '", "Alt + C"],
    resposta_correta: 1,
    dica: "A barra / é o símbolo de comentário em JS (//). Ctrl + / comenta e descomenta.",
  },
  {
    id: 41, categoria: "vscode", dificuldade: "Difícil", xp: 100,
    pergunta_imersiva: "ATALHO 11 // Silencie um BLOCO inteiro de código com comentário de bloco (/* */). Qual combinação?",
    codigo_base: "// Ação: Comment Block\n// Comentário de bloco /* */\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + /", "Shift + Alt + A", "Ctrl + Shift + /", "Alt + B"],
    resposta_correta: 1,
    dica: "Linha = Ctrl + /. BLOCO = Shift + Alt + A. Pense: A de 'Área' comentada.",
  },
  {
    id: 42, categoria: "vscode", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "ATALHO 12 // Seu código está uma bagunça de indentação. Formate o documento INTEIRO e deixe-o lindo.",
    codigo_base: "// Ação: Format Document\n// Formatar o código todo\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + F", "Shift + Alt + F", "Ctrl + Shift + I", "Alt + F"],
    resposta_correta: 1,
    dica: "F de FORMAT: Shift + Alt + F. Seu código fica 'beautifully formatted' num piscar de olhos.",
  },
  {
    id: 43, categoria: "vscode", dificuldade: "Difícil", xp: 100,
    pergunta_imersiva: "ATALHO 13 // Erro sublinhado no código? Abra as sugestões de correção rápida (Quick Fix) do VS Code.",
    codigo_base: "// Ação: Quick Fix\n// Sugestões de correção\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + .", "Ctrl + Q", "Alt + Enter", "Ctrl + ,"],
    resposta_correta: 0,
    dica: "Ctrl + . (ponto final). A lampadinha 💡 de sugestões abre com Ctrl + ponto.",
  },
  {
    id: 44, categoria: "vscode", dificuldade: "Difícil", xp: 100,
    pergunta_imersiva: "ATALHO 14 // Você está perdido num mar de chaves { }. Pule direto para o bracket correspondente!",
    codigo_base: "// Ação: Go to Matching Bracket\n// Pular para o { } par\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + B", "Ctrl + Shift + \\", "Ctrl + }", "Alt + M"],
    resposta_correta: 1,
    dica: "Lembra do Split Editor (Ctrl + \\)? Adicione Shift e você PULA para o bracket par: Ctrl + Shift + \\.",
  },
  {
    id: 45, categoria: "vscode", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "ATALHO 15 // Encontre uma palavra DENTRO do arquivo atual. O clássico dos clássicos.",
    codigo_base: "// Ação: Find in File\n// Buscar no arquivo atual\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + B", "Ctrl + F", "Ctrl + L", "Alt + F"],
    resposta_correta: 1,
    dica: "F de FIND. Ctrl + F funciona em quase todo software do planeta.",
  },
  {
    id: 46, categoria: "vscode", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "ATALHO 16 // Renomeie 'antigoNome' para 'novoNome' em todo o arquivo: busque e SUBSTITUA de uma vez.",
    codigo_base: "// Ação: Replace in File\n// Buscar e substituir\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + R", "Ctrl + H", "Ctrl + Shift + R", "Alt + R"],
    resposta_correta: 1,
    dica: "H de 'tHe replace' 😄 — brincadeira: vem de 'cHange'. Ctrl + H abre buscar-e-substituir.",
  },
  {
    id: 47, categoria: "vscode", dificuldade: "Fácil", xp: 50,
    pergunta_imersiva: "ATALHO 17 // Você tem 8 abas abertas. Vá para a PRÓXIMA aba sem tirar as mãos do teclado.",
    codigo_base: "// Ação: Next Tab\n// Ir para a próxima aba\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + Tab", "Alt + Tab", "Ctrl + →", "Tab"],
    resposta_correta: 0,
    dica: "Alt + Tab troca de PROGRAMA. Ctrl + Tab troca de ABA dentro do VS Code.",
  },
  {
    id: 48, categoria: "vscode", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "ATALHO 18 // Ops, passou da aba! Agora volte para a aba ANTERIOR.",
    codigo_base: "// Ação: Previous Tab\n// Voltar para a aba anterior\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + Shift + Tab", "Ctrl + ←", "Shift + Tab", "Ctrl + Alt + Tab"],
    resposta_correta: 0,
    dica: "Mesma lógica do Next Tab, mas com Shift para inverter a direção: Ctrl + Shift + Tab.",
  },
  {
    id: 49, categoria: "vscode", dificuldade: "Médio", xp: 75,
    pergunta_imersiva: "ATALHO 19 // O terminal integrado está ocupando metade da tela. Mostre/esconda o painel inferior.",
    codigo_base: "// Ação: Toggle Panel\n// Mostrar/esconder painel inferior\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + T", "Ctrl + J", "Ctrl + P", "Esc"],
    resposta_correta: 1,
    dica: "Ctrl + J abre e fecha o painel de baixo (terminal, problemas, output). J de 'Janela inferior'!",
  },
  {
    id: 50, categoria: "vscode", dificuldade: "Difícil", xp: 100,
    pergunta_imersiva: "ATALHO 20 // BOSS FINAL: o atalho que controla TODOS os outros. Abra a Command Palette, o centro de comando do VS Code.",
    codigo_base: "// Ação: Command Palette\n// O centro de comando de tudo\n\n[ PRESSIONE: ____ ]",
    opcoes: ["Ctrl + Space", "Ctrl + Shift + P", "Ctrl + Alt + C", "F1... quer dizer, hmm"],
    resposta_correta: 1,
    dica: "P de PALETTE. Ctrl + Shift + P abre a paleta onde você digita QUALQUER comando. Domine isso e você domina o VS Code.",
  },
];

export const XP_POR_NIVEL = 250;

export function nivelInfo(xp) {
  const nivel = Math.floor(xp / XP_POR_NIVEL) + 1;
  const dentro = xp % XP_POR_NIVEL;
  return { nivel, dentro, pct: Math.round((dentro / XP_POR_NIVEL) * 100) };
}
